- https://stackoverflow.com/questions/48915810/what-does-contiguous-do-in-pytorch
- https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch

In [1]:
import torch

Torch Official tutorial

https://pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html

### Example

In [11]:
# random tensor create
a = torch.randint(2,100,(2,3,2))

In [12]:
a

tensor([[[61, 82, 43,  ..., 59,  3, 84],
         [65, 57, 74,  ..., 61, 88, 64],
         [84, 87, 50,  ..., 67, 69, 53],
         ...,
         [18, 68, 66,  ..., 25,  5, 14],
         [72, 80, 21,  ..., 76, 86, 82],
         [41, 67, 84,  ..., 93, 99, 74]],

        [[ 8,  8, 92,  ..., 73, 18, 90],
         [13, 81,  2,  ..., 58, 37, 31],
         [ 8, 23, 32,  ..., 25, 87, 75],
         ...,
         [76, 19, 51,  ..., 26, 56, 30],
         [62, 63, 92,  ..., 54, 53, 97],
         [50, 66, 19,  ..., 28, 83, 61]],

        [[81, 36, 11,  ..., 65, 77, 62],
         [13, 48, 16,  ...,  5, 29, 38],
         [18, 70, 83,  ..., 67, 60, 97],
         ...,
         [ 9, 47, 80,  ..., 72, 58, 14],
         [31, 19, 77,  ..., 99, 20,  8],
         [ 6, 54, 19,  ..., 97, 43, 14]]])

In [13]:
a.shape

torch.Size([3, 24, 26])

In [16]:
# view of the tensor in the desired shape
a.view((2,2,3))

tensor([[[61, 82, 43],
         [12, 77, 25],
         [39, 15, 75],
         ...,
         [45, 49, 29],
         [63, 45, 98],
         [67, 69, 53]],

        [[58, 38, 84],
         [75, 86, 34],
         [94, 33, 35],
         ...,
         [26,  6, 30],
         [64, 65,  7],
         [50, 44, 11]],

        [[76, 80, 28],
         [29, 93,  3],
         [64, 30, 11],
         ...,
         [39, 28, 80],
         [66, 57, 69],
         [88, 59,  4]],

        ...,

        [[ 9, 42, 28],
         [92, 25, 96],
         [28, 25, 92],
         ...,
         [38, 55, 38],
         [79, 54, 90],
         [48, 26, 97]],

        [[35, 54, 71],
         [51, 32,  2],
         [43, 34, 54],
         ...,
         [94, 64, 51],
         [74, 44, 24],
         [49, 43, 43]],

        [[ 9, 47, 80],
         [76,  3, 76],
         [20, 41, 83],
         ...,
         [93, 32, 28],
         [24, 75, 42],
         [97, 43, 14]]])

In [5]:
a.view((3,2,2))

tensor([[[26, 91],
         [26, 98]],

        [[77, 60],
         [85, 42]],

        [[59,  6],
         [43, 60]]])

In [53]:
# flatten the tensor in a single dimension
a.flatten()

tensor([61, 56, 18, 29, 89, 21, 50, 57, 39, 74, 30, 74])

In [54]:
# Own understanding -> view is basically: 1) first flatten 2) then distribute the numbers as per the 
# desired shape from left to right
[67,73,41,75], [12,14,74,86], [81, 92, 51, 63]

([67, 73, 41, 75], [12, 14, 74, 86], [81, 92, 51, 63])

In [57]:
# tensor transpose 
at = a.T
at

tensor([[[61, 50],
         [18, 39],
         [89, 30]],

        [[56, 57],
         [29, 74],
         [21, 74]]])

In [58]:
at.shape

torch.Size([2, 3, 2])

In [63]:
at = a.view(3,2,2)

In [64]:
at.shape, at.T.shape

(torch.Size([3, 2, 2]), torch.Size([2, 2, 3]))

- As can be seen above, the tensor transpose basically creates a view of the tensor with shape of the original tensor's shape in reverse order (intuitively)

### Another Example

In [24]:
b = torch.randint(2,100,(1,3,5,7))

In [25]:
b.shape

torch.Size([1, 3, 5, 7])

In [26]:
b.view(3,1,5,7)

tensor([[[[27, 15, 73, 72, 52, 82, 13],
          [42,  4, 45, 66, 42, 60, 10],
          [15, 12, 25, 83, 69, 12, 15],
          [88, 99, 87, 43,  8,  6, 29],
          [24, 89, 67, 30, 25, 34, 95]]],


        [[[88, 35, 49, 78, 43, 68, 44],
          [55, 34, 71, 82, 15, 21,  2],
          [81, 57, 69, 72, 99, 47, 30],
          [34, 65,  3, 39, 28, 31, 39],
          [30, 95, 97, 23, 16,  9, 21]]],


        [[[ 2, 86, 24, 93, 93, 74, 62],
          [96, 81, 98, 52,  3, 15, 49],
          [41, 63, 16, 10, 72, 51, 86],
          [14, 11, 19, 17, 47, 24, 80],
          [63, 92, 30, 62, 52, 16, 92]]]])

In [27]:
b.T.shape

torch.Size([7, 5, 3, 1])

In [65]:
# applying transpose using torch module, this is pair wise, the two dimensions we want to swipe
torch.transpose(b, 1,3).shape

torch.Size([1, 7, 5, 3])

In [29]:
b.view(1,7,5,3)

tensor([[[[27, 15, 73],
          [72, 52, 82],
          [13, 42,  4],
          [45, 66, 42],
          [60, 10, 15]],

         [[12, 25, 83],
          [69, 12, 15],
          [88, 99, 87],
          [43,  8,  6],
          [29, 24, 89]],

         [[67, 30, 25],
          [34, 95, 88],
          [35, 49, 78],
          [43, 68, 44],
          [55, 34, 71]],

         [[82, 15, 21],
          [ 2, 81, 57],
          [69, 72, 99],
          [47, 30, 34],
          [65,  3, 39]],

         [[28, 31, 39],
          [30, 95, 97],
          [23, 16,  9],
          [21,  2, 86],
          [24, 93, 93]],

         [[74, 62, 96],
          [81, 98, 52],
          [ 3, 15, 49],
          [41, 63, 16],
          [10, 72, 51]],

         [[86, 14, 11],
          [19, 17, 47],
          [24, 80, 63],
          [92, 30, 62],
          [52, 16, 92]]]])

In [30]:
b.stride()

(105, 35, 7, 1)

In PyTorch, **contiguous** refers to the memory layout of a tensor. A tensor is said to be contiguous if its elements are stored in a contiguous block of memory in row-major order (C-style order). This ensures that accessing elements in a sequential manner is efficient.

### Key Points:
1. **Memory Layout**:
   - When you create or modify a tensor (e.g., via slicing, transposing, or reshaping), the resulting tensor may not have its elements stored in a contiguous block in memory.
   - Operations like `transpose` or `permute` only change how the data is *viewed* without changing its underlying memory layout.

2. **Why it Matters**:
   - Many PyTorch operations (like those involving GPUs or certain low-level functions) require tensors to be contiguous.
   - If a tensor is not contiguous, PyTorch will internally create a contiguous copy, which can impact performance.

3. **Checking Contiguity**:
   Use the `.is_contiguous()` method:
   ```python
   import torch
   a = torch.randn(3, 3)
   print(a.is_contiguous())  # True
   b = a.transpose(0, 1)
   print(b.is_contiguous())  # False
   ```

4. **Making a Tensor Contiguous**:
   Use `.contiguous()` to return a contiguous copy of the tensor:
   ```python
   c = b.contiguous()
   print(c.is_contiguous())  # True
   ```

### Example:
```python
# Original tensor
x = torch.tensor([[1, 2], [3, 4]])
print(x.is_contiguous())  # True

# Transposed tensor (non-contiguous)
y = x.t()
print(y.is_contiguous())  # False

# Making it contiguous
z = y.contiguous()
print(z.is_contiguous())  # True
```

### Summary:
Contiguity is important for performance and compatibility with certain operations. If you're unsure whether a tensor is contiguous or not, check using `.is_contiguous()`, and use `.contiguous()` if needed.

In [31]:
b.is_contiguous()

True

In [36]:
b.T.is_contiguous()

False

In [35]:
b.T.contiguous().is_contiguous()

True

In [39]:
b.shape

torch.Size([1, 3, 5, 7])

In [46]:
b_ = b.T

In [48]:
b_.shape

torch.Size([7, 5, 3, 1])

In [50]:
b_.squeeze().shape

torch.Size([7, 5, 3])

In [17]:
import inspect

In [23]:
inspect.getmodule(torch.transpose)

<module 'torch' from '/opt/conda/lib/python3.10/site-packages/torch/__init__.py'>

In [37]:
inspect.getmodule(b.is_contiguous)

#### Creating an uninitialized tensor

In [4]:
torch.Tensor(1) #<- a garbage value from memory may be. This is not initialized

tensor([6.2950e-12])

In [6]:
# For initialized random tensor
torch.zeros(1)

tensor([0.])

In [7]:
# or,
torch.ones(1)

tensor([1.])

In [9]:
#or 
torch.rand(1)

tensor([0.8554])

In [4]:
t = torch.tensor([[1, 2,3], [3, 4,5]])
# torch.gather(t, 1, torch.tensor([[0, 0], [1, 0]]))

In [9]:
t.gather(-1,torch.tensor([[1, 1], [1, 0]]))

tensor([[2, 2],
        [4, 3]])